# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Bug report ğŸ›
    url: https://github.com/johelder/react-native-input-code-otp/issues/new?template=bug_report.yml
    about: Report a reproducible bug or regression in this library.
  - name: Feature Request ğŸ’¡
    url: https://github.com/johelder/react-native-input-code-otp/discussions/new?category=ideas
    about: If you have a feature request, please create a new discussion on GitHub.
  - name: Discussions on GitHub ğŸ’¬
    url: https://github.com/johelder/react-native-input-code-otp/discussions
    about: If this library works as promised but you need help, please ask questions there.
